import { serviceDb } from "@/db/client";
import { aiBotRegistry } from "@/db/schema/ai-bot-registry";
import { sql } from "drizzle-orm";

export const BOT_REGISTRY_SEED = [
  {
    uaToken: "ChatGPT-User",
    matchMode: "substring" as const,
    vendor: "openai",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "retrieval" as const,
    isAgentUa: true,
    aiPlatform: "chatgpt",
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: "https://openai.com/chatgpt-user.json",
    ptrDomainSuffix: ".openai.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: "Highest-value signal — live user-initiated fetch",
  },
  {
    uaToken: "OAI-SearchBot",
    matchMode: "substring" as const,
    vendor: "openai",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "indexing" as const,
    isAgentUa: false,
    aiPlatform: "chatgpt",
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: "https://openai.com/searchbot.json",
    ptrDomainSuffix: ".openai.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "GPTBot",
    matchMode: "substring" as const,
    vendor: "openai",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: "https://openai.com/gptbot.json",
    ptrDomainSuffix: ".openai.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: "Training only",
  },
  {
    uaToken: "Claude-User",
    matchMode: "substring" as const,
    vendor: "anthropic",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "retrieval" as const,
    isAgentUa: true,
    aiPlatform: "claude",
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".anthropic.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: "Anthropic publishes no CIDR — FCrDNS primary (AA-04)",
  },
  {
    uaToken: "Claude-SearchBot",
    matchMode: "substring" as const,
    vendor: "anthropic",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "indexing" as const,
    isAgentUa: false,
    aiPlatform: "claude",
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".anthropic.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "ClaudeBot",
    matchMode: "substring" as const,
    vendor: "anthropic",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".anthropic.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "Perplexity-User",
    matchMode: "substring" as const,
    vendor: "perplexity",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "retrieval" as const,
    isAgentUa: true,
    aiPlatform: "perplexity",
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".perplexity.ai",
    expectedAsns: null,
    respectsRobots: null,
    notes: "Robots compliance disputed",
  },
  {
    uaToken: "PerplexityBot",
    matchMode: "substring" as const,
    vendor: "perplexity",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "indexing" as const,
    isAgentUa: false,
    aiPlatform: "perplexity",
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".perplexity.ai",
    expectedAsns: null,
    respectsRobots: null,
    notes: null,
  },
  {
    uaToken: "Google-NotebookLM",
    matchMode: "exact" as const,
    vendor: "google",
    crawlerTier: "emerging" as const,
    defaultPurpose: "retrieval" as const,
    isAgentUa: true,
    aiPlatform: "gemini",
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".google.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: "Headless-Chrome UA — needs exact match; a generic bot|crawl|spider regex MISSES it",
  },
  {
    uaToken: "Gemini-Deep-Research",
    matchMode: "substring" as const,
    vendor: "google",
    crawlerTier: "emerging" as const,
    defaultPurpose: "retrieval" as const,
    isAgentUa: true,
    aiPlatform: "gemini",
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".google.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "Googlebot",
    matchMode: "substring" as const,
    vendor: "google",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "indexing" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".google.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: "Feeds AI Overviews",
  },
  {
    uaToken: "bingbot",
    matchMode: "substring" as const,
    vendor: "microsoft",
    crawlerTier: "must_allow" as const,
    defaultPurpose: "indexing" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["cidr", "fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".search.msn.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: "Feeds Copilot",
  },
  {
    uaToken: "DuckAssistBot",
    matchMode: "substring" as const,
    vendor: "duckduckgo",
    crawlerTier: "emerging" as const,
    defaultPurpose: "indexing" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["cidr"],
    cidrSourceUrl: null,
    ptrDomainSuffix: null,
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "MistralAI-User",
    matchMode: "substring" as const,
    vendor: "mistral",
    crawlerTier: "emerging" as const,
    defaultPurpose: "retrieval" as const,
    isAgentUa: true,
    aiPlatform: null,
    verificationPaths: [],
    cidrSourceUrl: null,
    ptrDomainSuffix: null,
    expectedAsns: null,
    respectsRobots: null,
    notes: null,
  },
  {
    uaToken: "meta-externalagent",
    matchMode: "substring" as const,
    vendor: "meta",
    crawlerTier: "data" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["fcrdns", "asn"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".facebook.com",
    expectedAsns: [32934],
    respectsRobots: false,
    notes: "Ignores robots.txt",
  },
  {
    uaToken: "Bytespider",
    matchMode: "substring" as const,
    vendor: "bytedance",
    crawlerTier: "data" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["asn"],
    cidrSourceUrl: null,
    ptrDomainSuffix: null,
    expectedAsns: [396986],
    respectsRobots: false,
    notes: "Ignores robots.txt — ASN only verification",
  },
  {
    uaToken: "Amazonbot",
    matchMode: "substring" as const,
    vendor: "amazon",
    crawlerTier: "data" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".crawl.amazonbot.amazon",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "CCBot",
    matchMode: "substring" as const,
    vendor: "commoncrawl",
    crawlerTier: "data" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".commoncrawl.org",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "Applebot-Extended",
    matchMode: "substring" as const,
    vendor: "apple",
    crawlerTier: "data" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: ["fcrdns"],
    cidrSourceUrl: null,
    ptrDomainSuffix: ".applebot.apple.com",
    expectedAsns: null,
    respectsRobots: true,
    notes: null,
  },
  {
    uaToken: "cohere-ai",
    matchMode: "substring" as const,
    vendor: "cohere",
    crawlerTier: "data" as const,
    defaultPurpose: "training" as const,
    isAgentUa: false,
    aiPlatform: null,
    verificationPaths: [],
    cidrSourceUrl: null,
    ptrDomainSuffix: null,
    expectedAsns: null,
    respectsRobots: null,
    notes: null,
  },
];

export async function seedBotRegistry() {
  for (const bot of BOT_REGISTRY_SEED) {
    await serviceDb
      .insert(aiBotRegistry)
      .values({
        uaToken: bot.uaToken,
        matchMode: bot.matchMode,
        vendor: bot.vendor,
        crawlerTier: bot.crawlerTier,
        defaultPurpose: bot.defaultPurpose,
        isAgentUa: bot.isAgentUa,
        aiPlatform: bot.aiPlatform,
        verificationPaths: bot.verificationPaths,
        cidrSourceUrl: bot.cidrSourceUrl,
        ptrDomainSuffix: bot.ptrDomainSuffix,
        expectedAsns: bot.expectedAsns,
        respectsRobots: bot.respectsRobots,
        notes: bot.notes,
      })
      .onConflictDoUpdate({
        target: aiBotRegistry.uaToken,
        set: {
          vendor: sql`excluded.vendor`,
          crawlerTier: sql`excluded.crawler_tier`,
          defaultPurpose: sql`excluded.default_purpose`,
          isAgentUa: sql`excluded.is_agent_ua`,
          aiPlatform: sql`excluded.ai_platform`,
          verificationPaths: sql`excluded.verification_paths`,
          cidrSourceUrl: sql`excluded.cidr_source_url`,
          ptrDomainSuffix: sql`excluded.ptr_domain_suffix`,
          expectedAsns: sql`excluded.expected_asns`,
          respectsRobots: sql`excluded.respects_robots`,
          notes: sql`excluded.notes`,
          updatedAt: sql`now()`,
        },
      });
  }
}
