// Task VVV: every entry now carries an explicit sourceType -- "research"
// (a real, already-verified source, single-sourced from
// lib/methodology/verified-citations.ts so this list can't drift from
// lib/methodology/methods.ts the way "SE Ranking Dec 2025" did, task UUU)
// or "vunnara_estimate" (Sri's own call: the effectSizePct is Vunnara's
// estimate, not a claimed research figure -- no citationUrl, source reads
// "VisibleAU Original").
//
// Task KKK found all 22 "AutoGEO ICLR 2026" entries cited a real paper
// (arXiv 2510.11438, confirmed accepted ICLR 2026 via the authors' own
// GitHub) for topics it doesn't study -- AutoGEO is a content-REWRITING
// framework; nothing here is a content-rewriting method, so AutoGEO is not
// cited anywhere in this file. The same investigation found several other
// sources (Tinuiti/Profound/TEAM LEWIS/HubSpot, plus 3 Princeton-labelled
// entries whose specific claims don't match the real Aggarwal et al. paper)
// that couldn't be tied to a live, verifiable source when checked --
// relabelled vunnara_estimate rather than kept as an unverifiable citation.
//
// Post-ZZZ: effectSizePct (e.g. wikipedia-presence was 47.90) was invented
// precision inherited from the fabricated SE Ranking / AutoGEO data --
// kept as a number after UUU/VVV/YYY stripped the citations, but nobody
// at Vunnara ever measured or estimated it. Replaced here with impactTier
// ("high" | "medium" | "low"), assigned by genuine reasoning about each
// method's real AEO/GEO merit -- NOT by thresholding the old percentages
// (several tiers below deliberately diverge from what a mechanical bucket
// of the old number would have produced, e.g. remove-prompt-injections is
// "high" despite its old figure being one of the lowest, because the real
// risk is delisting, not a missed opportunity). See
// docs/ops/post-launch-db-hardening.md section 32 for the full proposal
// and rationale table.
import { VERIFIED_CITATIONS } from "@/lib/methodology/verified-citations";

const AGGARWAL = { source: VERIFIED_CITATIONS.aggarwalGEO.name, citationUrl: VERIFIED_CITATIONS.aggarwalGEO.url, sourceType: "research" as const };
const ESTIMATE = { source: "VisibleAU Original", citationUrl: null, sourceType: "vunnara_estimate" as const };

export const CITABILITY_METHODS = [
  {
    methodKey: "add-statistics-with-sources",
    title: "Add cited statistics with source links",
    description: "Include verifiable statistics with attribution from authoritative sources.",
    ...AGGARWAL,
    impactTier: "high",
    effectSizeNotes: "One of three top-performing GEO methods in the Princeton study (+30–40% Position-Adjusted Word Count)",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "add-expert-quotes",
    title: "Add attributed expert quotes",
    description: "Include direct quotes from named industry experts with credentials.",
    ...AGGARWAL,
    impactTier: "high",
    effectSizeNotes: "One of three top-performing GEO methods in the Princeton study (+30–40% Position-Adjusted Word Count)",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "add-authoritative-references",
    title: "Add authoritative source references",
    description: "Link to government, academic, or industry body sources.",
    ...AGGARWAL,
    impactTier: "high",
    effectSizeNotes: "Citing authoritative sources is part of the Princeton GEO study's citation-addition method (+30–40% Position-Adjusted Word Count)",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "wikipedia-presence",
    title: "Establish Wikipedia presence",
    description: "Create or improve a neutral, well-sourced Wikipedia article.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "Vunnara estimate — Wikipedia pages are frequently cited by ChatGPT for factual and informational queries",
    appliesTo: ["ChatGPT"],
  },
  {
    methodKey: "faq-in-main-content",
    title: "Add FAQ blocks in main page content",
    description: "Place FAQ content in the main body, not just schema markup.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — FAQ content in the main body is more quotable than schema-only",
    appliesTo: ["ChatGPT", "Gemini"],
  },
  {
    methodKey: "content-freshness",
    title: "Update content within last 2 months",
    description: "Keep pages updated with current dates, pricing, and contact info.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — fresh content signals currency to AI crawlers",
    appliesTo: ["ChatGPT", "Gemini", "Perplexity"],
  },
  {
    methodKey: "reddit-presence",
    title: "Genuine Reddit participation",
    description: "Contribute helpful answers in relevant subreddits.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — Perplexity frequently draws on Reddit discussions for real-world opinions and experiences",
    appliesTo: ["Perplexity"],
  },
  {
    methodKey: "medium-articles",
    title: "Publish how-to articles on Medium",
    description: "Write practical guides linking back to service pages.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Vunnara estimate — Gemini appears to favour accessible, first-party publishing platforms like Medium",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "linkedin-presence",
    title: "Maintain active LinkedIn company page",
    description: "Complete all sections and post regularly.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Vunnara estimate — active company pages support entity recognition and professional credibility signals",
    appliesTo: ["ChatGPT"],
  },
  {
    methodKey: "press-mentions",
    title: "Earn press mentions in trade media",
    description: "Pitch newsworthy stories to industry publications.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — earned media mentions create independent corroboration that can survive citation drift",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "comparison-content",
    title: "Publish comparison and vs content",
    description: "Create detailed comparison pages for high-intent queries.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "Vunnara estimate — comparison and \"best for\" queries are frequently answered by LLMs",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "schema-organization",
    title: "Add Organization schema markup",
    description: "Include complete Organization JSON-LD with all key attributes.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Helps Google AI Overviews indirectly via snippets",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "schema-local-business",
    title: "Add LocalBusiness schema markup",
    description: "Include LocalBusiness JSON-LD with NAP, hours, and service area.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Strengthens local entity recognition",
    appliesTo: ["Gemini", "ChatGPT"],
  },
  {
    methodKey: "schema-faq-page",
    title: "Add FAQPage schema markup",
    description: "Structure FAQ content with FAQPage JSON-LD markup.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Vunnara estimate — schema alone has limited impact without real content",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "schema-article",
    title: "Add Article schema markup",
    description: "Mark up blog and article pages with Article JSON-LD.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Improves article snippet selection",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "llms-txt-file",
    title: "Create and serve llms.txt",
    description: "Provide a structured llms.txt file for AI crawler consumption.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Emerging standard; early adoption signal",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "robots-allow-ai",
    title: "Allow AI crawlers in robots.txt",
    description: "Explicitly allow GPTBot, ClaudeBot, PerplexityBot access.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "Blocked bots cannot cite you at all",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "server-side-rendering",
    title: "Ensure server-side rendering",
    description: "Render content server-side so AI crawlers can read it.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "CSR pages invisible to most AI crawlers",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "answer-capsule-pattern",
    title: "Use the answer capsule pattern",
    description: "Follow question headings with a 20-25 word direct answer.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "Vunnara estimate — direct, well-formed answers are more likely to be quoted verbatim by AI engines",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "nap-consistency",
    title: "Ensure NAP consistency across directories",
    description: "Name, Address, Phone must match exactly across all listings.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Inconsistent NAP confuses entity resolution",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "au-directory-presence",
    title: "List on AU-specific directories",
    description: "Submit to hipages, Yellow Pages AU, ServiceSeeking, Word of Mouth.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "AU directories weight local AI responses",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "google-business-profile",
    title: "Complete Google Business Profile",
    description: "Fill all GBP sections including services, hours, photos.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "GBP feeds Google AI Overviews for local queries",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "content-depth-1500",
    title: "Ensure content depth (1500+ words)",
    description: "Key service pages should have substantial, detailed content.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — more substantial content gives AI engines more to cite",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "title-tag-optimization",
    title: "Optimize title tags for AI queries",
    description: "Include the primary service and location in page titles.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Title tags used in snippet selection",
    appliesTo: ["Gemini", "Perplexity"],
  },
  {
    methodKey: "meta-description-quality",
    title: "Write compelling meta descriptions",
    description: "50-160 character descriptions summarizing the page value proposition.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Meta descriptions feed search snippet selection",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "canonical-tags",
    title: "Set canonical tags correctly",
    description: "Prevent duplicate content confusion with proper canonicalization.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Prevents entity dilution from duplicate pages",
    appliesTo: ["Gemini", "ChatGPT"],
  },
  {
    methodKey: "og-tags-complete",
    title: "Complete Open Graph tags",
    description: "Include og:title, og:description, og:image on all pages.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Social signals feed AI entity graphs",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "internal-linking",
    title: "Strengthen internal linking structure",
    description: "Link between related service pages with descriptive anchor text.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — internal links help AI engines understand site structure and topical relationships",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "outbound-authority-links",
    title: "Link to authoritative external sources",
    description: "Reference government, academic, and industry body websites.",
    ...AGGARWAL,
    impactTier: "high",
    effectSizeNotes: "Citing authoritative external sources is part of the Princeton GEO study's citation-addition method (+30–40% Position-Adjusted Word Count)",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "author-attribution",
    title: "Add author bylines to content",
    description: "Include named authors with credentials on articles and guides.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Vunnara estimate — named author attribution signals expertise and accountability",
    appliesTo: ["ChatGPT", "Claude"],
  },
  {
    methodKey: "date-stamps",
    title: "Add last-updated dates to content",
    description: "Show when content was last reviewed or updated.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Vunnara estimate — visible freshness signals support content recency assessment",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "suburb-specific-pages",
    title: "Create suburb-specific landing pages",
    description: "Build dedicated pages for each service area suburb.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Suburb pages match local AI query patterns",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "remove-cta-overload",
    title: "Reduce excessive CTAs",
    description: "Keep CTAs under 7 per page to avoid spam signals.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "CTA overload correlates with lower AI citation rates",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "reduce-popup-density",
    title: "Minimize popups and overlays",
    description: "Remove or reduce intrusive popups that block content.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Popups degrade content accessibility for crawlers",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "fix-broken-links",
    title: "Fix broken outbound links",
    description: "Ensure all external links resolve correctly.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Broken links signal neglected content",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "reduce-ad-density",
    title: "Reduce ad density on key pages",
    description: "Keep ad containers under 3 per page on service pages.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "High ad density reduces content quality signals",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "remove-hidden-text",
    title: "Remove hidden text and invisible content",
    description: "Eliminate CSS-hidden text that could be flagged as manipulation.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "Hidden text triggers prompt injection detection",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "remove-prompt-injections",
    title: "Remove prompt injection attempts",
    description: "Eliminate any LLM-instruction text, invisible Unicode, or data-attr injections.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "Prompt injections can cause delisting",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "ai-txt-endpoint",
    title: "Create .well-known/ai.txt endpoint",
    description: "Publish machine-readable AI metadata at the emerging standard endpoint.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Emerging standard; early adoption advantage",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "ai-summary-json",
    title: "Create /ai/summary.json endpoint",
    description: "Publish structured brand summary for AI systems.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Structured data for AI consumption",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "ai-faq-json",
    title: "Create /ai/faq.json endpoint",
    description: "Publish FAQ data in machine-readable format for AI Q&A.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Structured FAQ for AI systems",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "ai-service-json",
    title: "Create /ai/service.json endpoint",
    description: "Publish service catalogue for local AI search.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Service data for local AI queries",
    appliesTo: ["ChatGPT", "Perplexity", "Gemini"],
  },
  {
    methodKey: "cdn-allow-ai",
    title: "Configure CDN to allow AI crawlers",
    description: "Ensure Cloudflare/Akamai/Vercel does not block AI bot user-agents.",
    ...ESTIMATE,
    impactTier: "high",
    effectSizeNotes: "CDN blocks prevent all AI crawling",
    appliesTo: ["ChatGPT", "Claude", "Perplexity", "Gemini"],
  },
  {
    methodKey: "sitemap-xml",
    title: "Maintain accurate sitemap.xml",
    description: "Include all indexable pages in an up-to-date sitemap.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Sitemap helps AI crawlers discover content",
    appliesTo: ["Gemini", "Perplexity"],
  },
  {
    methodKey: "hreflang-tags",
    title: "Add hreflang tags for AU content",
    description: "Signal Australian-specific content to search systems.",
    ...ESTIMATE,
    impactTier: "low",
    effectSizeNotes: "Localisation signal for regional queries",
    appliesTo: ["Gemini"],
  },
  {
    methodKey: "reduce-boilerplate",
    title: "Reduce boilerplate content ratio",
    description: "Ensure unique content exceeds 40% of total page text.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "High boilerplate reduces content quality signals",
    appliesTo: ["ChatGPT", "Perplexity"],
  },
  {
    methodKey: "abn-registration",
    title: "Verify ABN with Australian Business Register",
    description: "Ensure business name matches ABR records for entity verification.",
    ...ESTIMATE,
    impactTier: "medium",
    effectSizeNotes: "ABN verification strengthens AU entity signals",
    appliesTo: ["ChatGPT", "Gemini"],
  },
] as const;
