/**
 * Generates db/prod-fixes/seed-citability-methods-prod.sql from the current
 * corrected seed (db/seed/citability-methods/seed.ts). Every value in the
 * generated file is read from CITABILITY_METHODS -- nothing is hand-typed --
 * so the prod INSERTs can't silently drift from what the seed (and
 * lib/methodology/verified-citations.ts's provenance classification)
 * actually says.
 *
 * Connects to no database; only reads the seed module and writes stdout.
 * Usage:
 *   pnpm tsx scripts/ops/generate-citability-methods-prod-sql.ts > db/prod-fixes/seed-citability-methods-prod.sql
 */
import { CITABILITY_METHODS } from "../../db/seed/citability-methods/seed";

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlStringOrNull(value: string | null): string {
  return value === null ? "NULL" : sqlString(value);
}

function sqlNumericOrNull(value: string | null): string {
  return value === null ? "NULL" : value;
}

function sqlJsonbArray(values: readonly string[]): string {
  return `${sqlString(JSON.stringify(values))}::jsonb`;
}

const header = `-- Generated by scripts/ops/generate-citability-methods-prod-sql.ts from
-- db/seed/citability-methods/seed.ts (CITABILITY_METHODS, ${CITABILITY_METHODS.length} rows).
-- Every value below is read from that module, not hand-typed. Do NOT
-- hand-edit this file -- regenerate it instead if the seed changes.
--
-- Idempotent: ON CONFLICT (method_key) DO UPDATE -- safe to re-run, and
-- doubles as the refresh path if a method's provenance classification is
-- corrected later (DO UPDATE, not DO NOTHING, so a fix actually reaches
-- prod on a second run).
--
-- SRI: take a Neon snapshot/branch before running. Then run this file with
-- \`psql -f db/prod-fixes/seed-citability-methods-prod.sql "$PROD_DATABASE_URL"\`
-- (or paste into the Neon SQL editor, Production/neondb branch). NOT run
-- from Claude Code. Requires migration 0034 already applied (citation_url /
-- source_type columns must exist) -- see db/prod-fixes/0034-apply-prod.sql.

BEGIN;

INSERT INTO citability_methods
  (method_key, title, description, source, effect_size_pct, effect_size_notes, applies_to, citation_url, source_type)
VALUES
`;

const rowSql = CITABILITY_METHODS.map((m) => {
  const tuple = [
    sqlString(m.methodKey),
    sqlString(m.title),
    sqlString(m.description),
    sqlString(m.source),
    sqlNumericOrNull(m.effectSizePct),
    sqlStringOrNull(m.effectSizeNotes),
    sqlJsonbArray(m.appliesTo),
    sqlStringOrNull(m.citationUrl),
    sqlString(m.sourceType),
  ];
  return `  (${tuple.join(", ")})`;
}).join(",\n");

const footer = `
ON CONFLICT (method_key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  source = EXCLUDED.source,
  effect_size_pct = EXCLUDED.effect_size_pct,
  effect_size_notes = EXCLUDED.effect_size_notes,
  applies_to = EXCLUDED.applies_to,
  citation_url = EXCLUDED.citation_url,
  source_type = EXCLUDED.source_type;

COMMIT;

-- After this runs: 47 rows in citability_methods, 4 with source_type =
-- 'research' and a real citation_url (all arxiv.org/abs/2311.09735,
-- Aggarwal et al.), 43 with source_type = 'vunnara_estimate' and
-- citation_url = NULL. See db/prod-fixes/seed-citability-methods-verify.sql
-- for the exact verification queries.
`;

process.stdout.write(header + rowSql + footer);
