/**
 * Generates db/prod-fixes/seed-citability-methods-prod.sql from the current
 * corrected seed (db/seed/citability-methods/seed.ts). Every value in the
 * generated file is read from CITABILITY_METHODS -- nothing is hand-typed --
 * so the prod INSERTs can't silently drift from what the seed (and
 * lib/methodology/verified-citations.ts's provenance classification)
 * actually says.
 *
 * Post-ZZZ: effect_size_pct is deliberately NOT populated -- it was
 * invented precision (Sri's decision), superseded by impact_tier. Every
 * row explicitly sets effect_size_pct = NULL (including on DO UPDATE) so a
 * re-run also wipes any stale invented value a prior seed load left behind
 * -- see db/migrations/0035_citability_methods_impact_tier.sql and
 * docs/ops/post-launch-db-hardening.md section 32.
 *
 * Connects to no database; only reads the seed module and writes stdout.
 * Usage:
 *   pnpm tsx scripts/ops/generate-citability-methods-prod-sql.ts > db/prod-fixes/seed-citability-methods-prod.sql
 */
import { CITABILITY_METHODS } from "../../db/seed/citability-methods/seed";

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlStringOrNull(value: string | null): string {
  return value === null ? "NULL" : sqlString(value);
}

function sqlJsonbArray(values: readonly string[]): string {
  return `${sqlString(JSON.stringify(values))}::jsonb`;
}

const header = `-- Generated by scripts/ops/generate-citability-methods-prod-sql.ts from
-- db/seed/citability-methods/seed.ts (CITABILITY_METHODS, ${CITABILITY_METHODS.length} rows).
-- Every value below is read from that module, not hand-typed. Do NOT
-- hand-edit this file -- regenerate it instead if the seed changes.
--
-- Idempotent: ON CONFLICT (method_key) DO UPDATE -- safe to re-run, and
-- doubles as the refresh path if a method's provenance/tier is corrected
-- later (DO UPDATE, not DO NOTHING, so a fix actually reaches prod on a
-- second run). effect_size_pct is explicitly NULLed on every row (see
-- header comment in the generator) -- it is invented precision, replaced
-- by impact_tier.
--
-- SRI: take a Neon snapshot/branch before running. Then run this file with
-- \`psql -f db/prod-fixes/seed-citability-methods-prod.sql "$PROD_DATABASE_URL"\`
-- (or paste into the Neon SQL editor, Production/neondb branch). NOT run
-- from Claude Code. Requires migrations 0034 AND 0035 already applied
-- (citation_url / source_type / impact_tier columns must exist) -- see
-- db/prod-fixes/0034-apply-prod.sql and db/prod-fixes/0035-apply-prod.sql.

BEGIN;

INSERT INTO citability_methods
  (method_key, title, description, source, effect_size_pct, effect_size_notes, applies_to, citation_url, source_type, impact_tier)
VALUES
`;

const rowSql = CITABILITY_METHODS.map((m) => {
  const tuple = [
    sqlString(m.methodKey),
    sqlString(m.title),
    sqlString(m.description),
    sqlString(m.source),
    "NULL", // effect_size_pct: deprecated, invented precision -- never populated
    sqlStringOrNull(m.effectSizeNotes),
    sqlJsonbArray(m.appliesTo),
    sqlStringOrNull(m.citationUrl),
    sqlString(m.sourceType),
    sqlString(m.impactTier),
  ];
  return `  (${tuple.join(", ")})`;
}).join(",\n");

const footer = `
ON CONFLICT (method_key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  source = EXCLUDED.source,
  effect_size_pct = EXCLUDED.effect_size_pct,
  effect_size_notes = EXCLUDED.effect_size_notes,
  applies_to = EXCLUDED.applies_to,
  citation_url = EXCLUDED.citation_url,
  source_type = EXCLUDED.source_type,
  impact_tier = EXCLUDED.impact_tier;

COMMIT;

-- After this runs: 47 rows in citability_methods, 4 with source_type =
-- 'research' and a real citation_url (all arxiv.org/abs/2311.09735,
-- Aggarwal et al.), 43 with source_type = 'vunnara_estimate' and
-- citation_url = NULL. Every row has a valid impact_tier
-- ('high'/'medium'/'low') and effect_size_pct = NULL. See
-- db/prod-fixes/seed-citability-methods-verify.sql for the exact
-- verification queries.
`;

process.stdout.write(header + rowSql + footer);
