import type { CrawlPage } from "@/lib/crawler/types";

export interface LlmstxtResult {
  content: string;
  depthScore: number;
}

export function generateLlmsTxt(
  brandName: string,
  brandDomain: string,
  pages: CrawlPage[],
  robotsTxt: string | null,
): LlmstxtResult {
  const lines: string[] = [];
  let depthScore = 0;

  lines.push(`# ${brandName}`);
  lines.push(`> AI-readable site map for ${brandDomain}`);
  lines.push("");

  if (robotsTxt) {
    depthScore += 2;
  }

  lines.push("## Pages");
  for (const page of pages.slice(0, 20)) {
    const desc = page.excerpt.replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim().slice(0, 100);
    lines.push(`- [${page.title || page.url}](${page.url}): ${desc}`);
    depthScore += 1;
  }
  depthScore = Math.min(depthScore, 14);

  const hasAbout = pages.some((p) => /\/about/i.test(p.url));
  const hasContact = pages.some((p) => /\/contact/i.test(p.url));
  const hasFaq = pages.some((p) => /\/faq/i.test(p.url));
  const hasServices = pages.some((p) => /\/services/i.test(p.url));

  if (hasAbout) depthScore += 1;
  if (hasContact) depthScore += 1;
  if (hasFaq) depthScore += 1;
  if (hasServices) depthScore += 1;

  depthScore = Math.min(depthScore, 18);

  lines.push("");
  lines.push(`## Generated`);
  lines.push(`Generated by VisibleAU for ${brandDomain}`);

  return {
    content: lines.join("\n"),
    depthScore,
  };
}
