export const AU_ALLIED_HEALTH_PROMPTS = [
  // --- service-discovery (24) ---
  {
    rank: 1,
    promptTemplate: "Who are the best physiotherapists in {location}?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 2,
    promptTemplate: "Top-rated psychologists in {location} accepting new patients?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 3,
    promptTemplate: "Recommended dietitians in {location} who specialise in gut health?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 4,
    promptTemplate: "Best physiotherapy clinic near {location}?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 5,
    promptTemplate: "Who are the most trusted chiropractors in {location} for back pain?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 6,
    promptTemplate: "Best occupational therapists in {location} registered with AHPRA?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 7,
    promptTemplate: "Top podiatrists in {location} for sports injuries?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 8,
    promptTemplate: "Best speech pathologists in {location} for children?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 9,
    promptTemplate: "Who are the best exercise physiologists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 10,
    promptTemplate: "Best remedial massage therapists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 11,
    promptTemplate: "Top audiologists in {location} for hearing tests?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 12,
    promptTemplate: "Best naturopaths in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 13,
    promptTemplate: "Who does clinical Pilates in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 14,
    promptTemplate: "Best osteopaths in {location} for neck pain?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 15,
    promptTemplate: "Paediatric physiotherapists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 16,
    promptTemplate: "Best hand therapists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 17,
    promptTemplate: "Who does hydrotherapy in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 18,
    promptTemplate: "Best pelvic floor physiotherapists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 19,
    promptTemplate: "Neuropsychologists in {location} for ADHD assessment?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 20,
    promptTemplate: "Who does dry needling in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 21,
    promptTemplate: "Best myotherapists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 22,
    promptTemplate: "Orthotists and prosthetists in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 23,
    promptTemplate: "Best mental health social workers in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 24,
    promptTemplate: "Acupuncturists in {location} with AHPRA registration?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  // --- recommendation (16) ---
  {
    rank: 25,
    promptTemplate: "Can you recommend a good physiotherapist in {location} for knee rehab?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 26,
    promptTemplate: "Who would you recommend for anxiety treatment in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 27,
    promptTemplate: "Is {brand} a good allied health provider in Australia?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 28,
    promptTemplate: "Tell me about {domain} — would you recommend them for physiotherapy?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 29,
    promptTemplate: "Recommend a chiropractor for sciatica in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 30,
    promptTemplate: "Who would you suggest for children's speech therapy in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 31,
    promptTemplate: "Recommend a dietitian for sports nutrition in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 32,
    promptTemplate:
      "Who do you recommend for occupational therapy for NDIS participants in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 33,
    promptTemplate: "Recommend a psychologist for couples counselling in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 34,
    promptTemplate: "Who would you suggest for post-surgery rehab physio in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 35,
    promptTemplate: "Recommend a podiatrist for orthotics in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 36,
    promptTemplate: "Who do you recommend for chronic pain management in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 37,
    promptTemplate: "Recommend an exercise physiologist for diabetes management in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 38,
    promptTemplate: "Who would you suggest for workplace ergonomic assessment in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 39,
    promptTemplate: "Recommend a psychologist who specialises in trauma (EMDR) in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 40,
    promptTemplate: "Who do you recommend for vestibular rehab in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  // --- comparison (16) ---
  {
    rank: 41,
    promptTemplate:
      "{brand} vs {competitors} — which physiotherapy clinic is better in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 42,
    promptTemplate: "Compare the best psychologists in {location} — who stands out?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 43,
    promptTemplate: "How does {brand} compare to other allied health providers in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 44,
    promptTemplate: "Physiotherapy vs chiropractic for back pain in {location} — which is better?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 45,
    promptTemplate:
      "Compare physio clinics in {location} — solo practitioner vs multi-disciplinary?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 46,
    promptTemplate: "{brand} vs {competitors} for sports physiotherapy?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 47,
    promptTemplate: "Compare psychologists vs counsellors for anxiety in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 48,
    promptTemplate: "Which dietitian in {location} is best for weight management?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 49,
    promptTemplate: "Compare osteopathy vs physiotherapy for neck pain in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 50,
    promptTemplate: "{brand} vs {competitors} — which has better patient outcomes?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 51,
    promptTemplate: "Compare NDIS physiotherapy providers in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 52,
    promptTemplate: "Which speech pathologist in {location} is best for autism support?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 53,
    promptTemplate: "Compare exercise physiology clinics in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 54,
    promptTemplate: "How does {brand} compare to hospital outpatient physio in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 55,
    promptTemplate: "Compare podiatry clinics in {location} — who offers gait analysis?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 56,
    promptTemplate: "{brand} vs {competitors} for clinical Pilates?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  // --- service-specific (20) ---
  {
    rank: 57,
    promptTemplate: "Physiotherapist for ACL reconstruction rehab in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 58,
    promptTemplate: "Psychologist for CBT therapy in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 59,
    promptTemplate: "Dietitian for FODMAP diet guidance in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 60,
    promptTemplate: "Chiropractor for pregnancy-related back pain in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 61,
    promptTemplate: "Physiotherapist for TMJ (jaw) dysfunction in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 62,
    promptTemplate: "Psychologist for ADHD assessment and diagnosis in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 63,
    promptTemplate: "OT for sensory processing disorder in children in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 64,
    promptTemplate: "Physiotherapist for pre and postnatal care in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 65,
    promptTemplate: "Speech pathologist for stuttering therapy in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 66,
    promptTemplate: "Podiatrist for diabetic foot care in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 67,
    promptTemplate: "Psychologist for eating disorder treatment in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 68,
    promptTemplate: "Physiotherapist for Parkinson's disease in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 69,
    promptTemplate: "Dietitian for gestational diabetes in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 70,
    promptTemplate: "OT for return-to-work rehabilitation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 71,
    promptTemplate: "Physiotherapist for shoulder impingement in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 72,
    promptTemplate: "Psychologist for grief counselling in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 73,
    promptTemplate: "Exercise physiologist for cardiac rehab in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 74,
    promptTemplate: "Speech pathologist for swallowing difficulties in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 75,
    promptTemplate: "Physiotherapist for vertigo and balance issues in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 76,
    promptTemplate: "Psychologist for perinatal mental health in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  // --- pricing (10) ---
  {
    rank: 77,
    promptTemplate: "How much does a private physiotherapy session cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 78,
    promptTemplate: "What is the average cost of a psychology session in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 79,
    promptTemplate: "How much does a dietitian consultation cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 80,
    promptTemplate: "Cost of chiropractic treatment in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 81,
    promptTemplate: "How much does a podiatry consultation cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 82,
    promptTemplate: "What is the gap fee for physiotherapy under Medicare in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 83,
    promptTemplate: "How much does an ADHD assessment cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 84,
    promptTemplate: "Cost of remedial massage with health fund rebate in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 85,
    promptTemplate: "How much does a speech pathology session cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 86,
    promptTemplate: "Average cost of exercise physiology sessions in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  // --- reviews (8) ---
  {
    rank: 87,
    promptTemplate: "Which physiotherapy clinics in {location} have the best reviews?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 88,
    promptTemplate: "Best-reviewed psychologists in {location} on Google?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 89,
    promptTemplate: "What do patients say about {brand}?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 90,
    promptTemplate: "Which {location} chiropractors have the most 5-star Google reviews?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 91,
    promptTemplate: "Best-reviewed dietitians in {location}?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 92,
    promptTemplate: "What are the reviews for {brand} on HealthEngine?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 93,
    promptTemplate: "Highest-rated OTs in {location} on Google Maps?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 94,
    promptTemplate: "What do patients say about {domain}?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  // --- problem-driven (6) ---
  {
    rank: 95,
    promptTemplate: "I have lower back pain that won't go away — who should I see in {location}?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 96,
    promptTemplate: "My child is not speaking at age 3 — where should I go in {location}?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 97,
    promptTemplate: "I've been feeling anxious and depressed — who can help in {location}?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 98,
    promptTemplate: "I have plantar fasciitis — which podiatrist in {location} is best?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 99,
    promptTemplate:
      "I need help managing my weight — dietitian or exercise physiologist in {location}?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 100,
    promptTemplate: "I keep getting headaches — should I see a physio or chiro in {location}?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  // --- compliance (4) ---
  {
    rank: 101,
    promptTemplate: "Which {location} psychology practices offer bulk-billing or Medicare rebates?",
    category: "compliance",
    expectedMentionType: "listed",
  },
  {
    rank: 102,
    promptTemplate: "Is {brand} registered with AHPRA?",
    category: "compliance",
    expectedMentionType: "recommended",
  },
  {
    rank: 103,
    promptTemplate: "How do I check if a physiotherapist is AHPRA-registered in {location}?",
    category: "compliance",
    expectedMentionType: "listed",
  },
  {
    rank: 104,
    promptTemplate: "Which allied health providers in {location} accept NDIS clients?",
    category: "compliance",
    expectedMentionType: "listed",
  },
] as const;
