export const AU_SAAS_PROMPTS = [
  // --- service-discovery (24) ---
  {
    rank: 1,
    promptTemplate: "What are the best project management tools for Australian small businesses?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 2,
    promptTemplate: "Top CRM software that integrates with Xero for Australian companies?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 3,
    promptTemplate: "Best invoicing and accounting software for Australian freelancers?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 4,
    promptTemplate: "What B2B SaaS tools are popular among Australian startups?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 5,
    promptTemplate: "Recommended HR software for small Australian businesses?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 6,
    promptTemplate: "Best helpdesk software for Australian customer support teams?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 7,
    promptTemplate: "Top marketing automation tools used by Australian agencies?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 8,
    promptTemplate: "Best time tracking software for Australian consultancies?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 9,
    promptTemplate: "What e-commerce platforms do Australian businesses use?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 10,
    promptTemplate: "Best document management software for Australian law firms?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 11,
    promptTemplate: "Top email marketing tools for Australian SMBs?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 12,
    promptTemplate: "Best inventory management software for Australian retailers?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 13,
    promptTemplate: "What ERP systems do Australian mid-market companies use?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 14,
    promptTemplate: "Best appointment booking software for Australian service businesses?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 15,
    promptTemplate: "Top proposal software for Australian agencies?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 16,
    promptTemplate: "Best fleet management software for Australian logistics companies?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 17,
    promptTemplate: "What learning management systems do Australian companies use?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 18,
    promptTemplate: "Best field service management software for Australian tradies?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 19,
    promptTemplate: "Top survey and feedback tools for Australian businesses?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 20,
    promptTemplate: "Best payroll software for Australian businesses with STP compliance?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 21,
    promptTemplate: "What collaboration tools do Australian remote teams use?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 22,
    promptTemplate: "Best construction project management software used in Australia?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 23,
    promptTemplate: "Top cybersecurity tools for Australian small businesses?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 24,
    promptTemplate: "Best POS systems for Australian hospitality businesses?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  // --- recommendation (16) ---
  {
    rank: 25,
    promptTemplate: "Is {brand} a good software tool for Australian businesses? What do users say?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 26,
    promptTemplate: "Tell me about {domain} — is it a reputable SaaS product used in Australia?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 27,
    promptTemplate: "Would you recommend {brand} for project management in an Australian agency?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 28,
    promptTemplate: "Should an Australian startup use {brand} for their CRM?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 29,
    promptTemplate: "Is {brand} suitable for Australian accounting and BAS compliance?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 30,
    promptTemplate: "Would you recommend {brand} for Australian HR and leave management?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 31,
    promptTemplate: "Is {brand} a good choice for Australian e-commerce businesses?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 32,
    promptTemplate: "Should an Australian consulting firm use {brand} for time tracking?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 33,
    promptTemplate: "Is {brand} worth it for Australian marketing teams?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 34,
    promptTemplate: "Would you recommend {brand} for Australian field service teams?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 35,
    promptTemplate: "Is {brand} suitable for Australian NDIS providers?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 36,
    promptTemplate: "Should an Australian real estate agency use {brand}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 37,
    promptTemplate: "Is {brand} good for Australian strata management companies?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 38,
    promptTemplate: "Would you recommend {brand} for an Australian nonprofit?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 39,
    promptTemplate: "Is {brand} a reliable tool for Australian legal firms?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 40,
    promptTemplate: "Should an Australian SaaS company use {brand} for customer support?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  // --- comparison (20) ---
  {
    rank: 41,
    promptTemplate: "What are the best alternatives to Salesforce for Australian SMBs?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 42,
    promptTemplate:
      "Which project management tools are best suited for Australian time zones and teams?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 43,
    promptTemplate: "{brand} vs {competitors} — which is better for Australian businesses?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 44,
    promptTemplate: "Compare {brand} with {competitors} for accounting in Australia?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 45,
    promptTemplate: "Xero vs MYOB vs QuickBooks — which is best for Australian businesses?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 46,
    promptTemplate: "{brand} vs {competitors} for HR management in Australia?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 47,
    promptTemplate: "Compare CRM platforms for Australian agencies?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 48,
    promptTemplate: "Monday.com vs Asana vs ClickUp for Australian teams?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 49,
    promptTemplate: "{brand} vs {competitors} for email marketing?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 50,
    promptTemplate:
      "Compare e-commerce platforms for Australian retailers — Shopify vs BigCommerce?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 51,
    promptTemplate: "{brand} vs {competitors} for time tracking and billing?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 52,
    promptTemplate: "Compare helpdesk tools — Zendesk vs Freshdesk for Australian teams?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 53,
    promptTemplate: "{brand} vs {competitors} for inventory management in Australia?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 54,
    promptTemplate:
      "Compare payroll platforms for Australian businesses — Employment Hero vs KeyPay?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 55,
    promptTemplate: "{brand} vs {competitors} — which has better Australian support?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 56,
    promptTemplate: "Compare proposal tools — Proposify vs PandaDoc for Australian agencies?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 57,
    promptTemplate: "{brand} vs {competitors} for construction management?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 58,
    promptTemplate: "Compare LMS platforms for Australian corporate training?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 59,
    promptTemplate: "{brand} vs {competitors} for document management?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 60,
    promptTemplate: "Compare POS systems for Australian cafes — Square vs Lightspeed?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  // --- service-specific (18) ---
  {
    rank: 61,
    promptTemplate: "What SaaS tools do Australian agencies use for client reporting?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 62,
    promptTemplate: "Best software for managing BAS lodgement in Australia?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 63,
    promptTemplate: "SaaS tools for Australian builders doing job costing?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 64,
    promptTemplate: "Best rostering software for Australian hospitality businesses?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 65,
    promptTemplate: "What tools do Australian real estate agents use for property CRM?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 66,
    promptTemplate: "Best NDIS plan management software for Australian providers?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 67,
    promptTemplate: "What compliance management tools do Australian financial advisors use?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 68,
    promptTemplate: "Best practice management software for Australian allied health clinics?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 69,
    promptTemplate: "What ATS (applicant tracking) do Australian recruiters use?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 70,
    promptTemplate: "Best subscription billing software for Australian SaaS companies?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 71,
    promptTemplate: "What tools do Australian logistics companies use for route optimisation?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 72,
    promptTemplate: "Best OKR and goal-tracking software for Australian startups?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 73,
    promptTemplate: "What asset management tools do Australian councils use?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 74,
    promptTemplate: "Best digital signature tools compliant with Australian e-signature laws?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 75,
    promptTemplate: "What warehouse management systems do Australian 3PLs use?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 76,
    promptTemplate: "Best board management software for Australian organisations?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 77,
    promptTemplate: "What workflow automation tools do Australian operations teams use?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 78,
    promptTemplate: "Best visitor management software for Australian offices?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  // --- pricing (10) ---
  {
    rank: 79,
    promptTemplate: "How much does CRM software cost for an Australian small business?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 80,
    promptTemplate:
      "What is the average cost of project management software per user in Australia?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 81,
    promptTemplate: "How much does {brand} cost in Australian dollars?",
    category: "pricing",
    expectedMentionType: "recommended",
  },
  {
    rank: 82,
    promptTemplate: "Affordable accounting software for Australian sole traders — under $30/month?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 83,
    promptTemplate: "How much does HR software cost per employee in Australia?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 84,
    promptTemplate: "Free vs paid project management tools for Australian startups?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 85,
    promptTemplate: "How much does helpdesk software cost for a 10-person Australian team?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 86,
    promptTemplate: "What is the total cost of ownership for {brand} in Australia?",
    category: "pricing",
    expectedMentionType: "recommended",
  },
  {
    rank: 87,
    promptTemplate: "Best free CRM tools suitable for Australian small businesses?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 88,
    promptTemplate: "How much does e-commerce platform hosting cost in Australia?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  // --- reviews (8) ---
  {
    rank: 89,
    promptTemplate: "What do Australian businesses say about {brand}?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 90,
    promptTemplate: "Best-reviewed CRM software on G2 used by Australian companies?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 91,
    promptTemplate: "What are the reviews for {domain} from Australian users?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 92,
    promptTemplate: "Highest-rated project management tools on Capterra for Australian teams?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 93,
    promptTemplate: "What do Australian accountants think of {brand}?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 94,
    promptTemplate: "Best-reviewed payroll software for Australian businesses?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 95,
    promptTemplate: "What do Australian HR managers say about {brand}?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 96,
    promptTemplate: "Best-reviewed appointment booking software by Australian service businesses?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  // --- problem-driven (8) ---
  {
    rank: 97,
    promptTemplate: "My Australian business needs to automate invoicing — what should I use?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 98,
    promptTemplate: "I'm losing track of leads — best CRM for a small Australian business?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 99,
    promptTemplate: "My team is spread across Australian cities — best collaboration tool?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 100,
    promptTemplate: "I need to comply with STP Phase 2 — which payroll software handles this?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 101,
    promptTemplate:
      "My agency needs better client reporting — what tools do Australian agencies use?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 102,
    promptTemplate:
      "I'm migrating from spreadsheets — best project management tool for an Australian SMB?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 103,
    promptTemplate:
      "My e-commerce store needs a better checkout — what platforms work in Australia?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  {
    rank: 104,
    promptTemplate: "I need NDIS-compliant practice management — what do Australian providers use?",
    category: "problem-driven",
    expectedMentionType: "recommended",
  },
  // --- compliance (4) ---
  {
    rank: 105,
    promptTemplate: "Which Australian SaaS tools are SOC 2 compliant?",
    category: "compliance",
    expectedMentionType: "listed",
  },
  {
    rank: 106,
    promptTemplate: "Is {brand} compliant with Australian Privacy Act requirements?",
    category: "compliance",
    expectedMentionType: "recommended",
  },
  {
    rank: 107,
    promptTemplate: "Which CRM platforms store data in Australian data centres?",
    category: "compliance",
    expectedMentionType: "listed",
  },
  {
    rank: 108,
    promptTemplate: "Is {brand} compliant with IRAP (Australian government security)?",
    category: "compliance",
    expectedMentionType: "recommended",
  },
] as const;
