export const AU_TRADIES_PROMPTS = [
  // --- service-discovery (28) ---
  {
    rank: 1,
    promptTemplate: "Who are the best plumbers in {location}?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 2,
    promptTemplate: "I need an emergency electrician near {location}. Who should I call?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 3,
    promptTemplate: "Best licensed builders in {location} for residential renovations?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 4,
    promptTemplate: "Can you recommend a reliable plumber near {location}?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 5,
    promptTemplate: "Who are the most trusted HVAC technicians in {location}?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 6,
    promptTemplate: "Top-rated roof plumbers in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 7,
    promptTemplate: "Best gasfitters in {location} for appliance installation?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 8,
    promptTemplate: "Who should I call for a blocked drain in {location}?",
    category: "service-discovery",
    expectedMentionType: "recommended",
  },
  {
    rank: 9,
    promptTemplate: "Best tilers for bathroom renovations in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 10,
    promptTemplate: "Who are the best painters in {location} for interior work?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 11,
    promptTemplate: "Best split system air conditioning installers in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 12,
    promptTemplate: "Who does solar panel installation in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 13,
    promptTemplate: "Best fencing contractors in {location} for Colorbond fencing?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 14,
    promptTemplate: "Who are the best concreters in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 15,
    promptTemplate: "Top landscapers in {location} for backyard makeovers?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 16,
    promptTemplate: "Best plasterers in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 17,
    promptTemplate: "Who does asbestos removal in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 18,
    promptTemplate: "Best glaziers in {location} for window replacement?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 19,
    promptTemplate: "Top bricklayers in {location} for retaining walls?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 20,
    promptTemplate: "Who does commercial plumbing in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 21,
    promptTemplate: "Best carpenters in {location} for custom cabinetry?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 22,
    promptTemplate: "Top locksmiths in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 23,
    promptTemplate: "Who does demolition work in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 24,
    promptTemplate: "Best arborists in {location} for tree removal?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 25,
    promptTemplate: "Who installs ducted air conditioning in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 26,
    promptTemplate: "Best waterproofers in {location} for bathrooms?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 27,
    promptTemplate: "Top pest control companies in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  {
    rank: 28,
    promptTemplate: "Who are the best pool builders in {location}?",
    category: "service-discovery",
    expectedMentionType: "listed",
  },
  // --- recommendation (18) ---
  {
    rank: 29,
    promptTemplate: "Can you recommend a good plumber in {location} for a bathroom reno?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 30,
    promptTemplate: "Who would you recommend for electrical rewiring in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 31,
    promptTemplate: "Which builder would you recommend for a granny flat in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 32,
    promptTemplate: "Recommend a plumber for hot water system replacement in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 33,
    promptTemplate: "Who would you suggest for a kitchen renovation in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 34,
    promptTemplate: "Is {brand} a reputable tradesperson in Australia? What do customers say?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 35,
    promptTemplate: "Can you tell me about {domain} — are they a good choice for plumbing?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 36,
    promptTemplate: "Who would you recommend for a deck build in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 37,
    promptTemplate: "Recommend an electrician for switchboard upgrades in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 38,
    promptTemplate: "Who would you suggest for strata plumbing in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 39,
    promptTemplate: "Can you recommend a tiler for outdoor areas in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 40,
    promptTemplate: "Recommend an air conditioning technician for ducted systems in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 41,
    promptTemplate: "Who do you recommend for gutter replacement in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 42,
    promptTemplate: "Recommend a good handyman service in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 43,
    promptTemplate: "Who would you suggest for roof restoration in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 44,
    promptTemplate:
      "Can you recommend a reliable electrician for EV charger installation in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 45,
    promptTemplate: "Who do you recommend for bathroom waterproofing in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  {
    rank: 46,
    promptTemplate: "Recommend a gas plumber for cooktop installation in {location}?",
    category: "recommendation",
    expectedMentionType: "recommended",
  },
  // --- comparison (22) ---
  {
    rank: 47,
    promptTemplate: "{brand} vs {competitors} — which is better for plumbing in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 48,
    promptTemplate: "Compare the best electricians in {location} — who stands out?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 49,
    promptTemplate: "How does {brand} compare to other plumbers in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 50,
    promptTemplate: "What are the best alternatives to big plumbing franchises in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 51,
    promptTemplate: "{brand} vs {competitors} for emergency electrical work in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 52,
    promptTemplate: "Compare local builders vs national builders in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 53,
    promptTemplate: "Is {brand} better value than {competitors} for renovations?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 54,
    promptTemplate: "Which plumber has the fastest response time in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 55,
    promptTemplate: "Compare HVAC brands for split system installs in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 56,
    promptTemplate:
      "Who is better for roofing — local tradies or franchise companies in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 57,
    promptTemplate: "Compare solar installers in {location} — price vs quality?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 58,
    promptTemplate: "{brand} vs {competitors} — which offers better warranty?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 59,
    promptTemplate: "Compare pool builders in {location} — fibreglass vs concrete?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 60,
    promptTemplate: "Which landscaper in {location} is best for small backyards?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 61,
    promptTemplate: "Compare fencing contractors in {location} — who is most affordable?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 62,
    promptTemplate: "How does {brand} compare to hipages tradespeople in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 63,
    promptTemplate: "Compare painting quotes in {location} — what's a fair price?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 64,
    promptTemplate: "{brand} vs {competitors} for bathroom renovation in {location}?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 65,
    promptTemplate: "Which electrician in {location} is best for new home wiring?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 66,
    promptTemplate: "Compare tiling companies in {location} — who does the best work?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 67,
    promptTemplate: "How does {brand} compare to Airtasker tradespeople?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  {
    rank: 68,
    promptTemplate: "{brand} vs {competitors} — who has better Google reviews?",
    category: "comparison",
    expectedMentionType: "comparison",
  },
  // --- service-specific (24) ---
  {
    rank: 69,
    promptTemplate: "Plumber for hot water system installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 70,
    promptTemplate: "Electrician for safety switch installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 71,
    promptTemplate: "Builder for granny flat construction in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 72,
    promptTemplate: "Who does gas fitting and compliance certificates in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 73,
    promptTemplate: "Plumber for sewer line relining in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 74,
    promptTemplate: "Electrician for commercial fit-out in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 75,
    promptTemplate: "Who does backflow prevention testing in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 76,
    promptTemplate: "Air conditioning service and regas in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 77,
    promptTemplate: "Plumber for rainwater tank installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 78,
    promptTemplate: "Electrician for smoke alarm compliance in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 79,
    promptTemplate: "Builder for knockdown rebuild in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 80,
    promptTemplate: "Who does stormwater drainage installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 81,
    promptTemplate: "Plumber for CCTV drain camera inspection in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 82,
    promptTemplate: "Electrician for level 2 service provider work in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 83,
    promptTemplate: "Who does underpinning and restumping in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 84,
    promptTemplate: "Plumber for TMV (thermostatic mixing valve) installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 85,
    promptTemplate: "Roofer for Colorbond roof replacement in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 86,
    promptTemplate: "Electrician for data cabling and networking in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 87,
    promptTemplate: "Builder for dual occupancy builds in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 88,
    promptTemplate: "Who does garage door installation and repair in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 89,
    promptTemplate: "Plumber for grease trap cleaning in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 90,
    promptTemplate: "Electrician for 3-phase power installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 91,
    promptTemplate: "Who does retaining wall construction in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  {
    rank: 92,
    promptTemplate: "Plumber for water filtration system installation in {location}?",
    category: "service-specific",
    expectedMentionType: "listed",
  },
  // --- emergency (12) ---
  {
    rank: 93,
    promptTemplate: "24/7 emergency plumber near {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 94,
    promptTemplate: "Burst pipe emergency plumber in {location} — who to call right now?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 95,
    promptTemplate: "Emergency electrician for power outage in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 96,
    promptTemplate: "After-hours plumber in {location} for hot water emergency?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 97,
    promptTemplate: "Who does emergency gas leak repairs in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 98,
    promptTemplate: "Emergency locksmith in {location} — 24-hour service?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 99,
    promptTemplate: "Emergency blocked toilet plumber in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 100,
    promptTemplate: "Emergency roof leak repair in {location} — who comes out fast?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 101,
    promptTemplate: "After-hours electrician for sparking outlet in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 102,
    promptTemplate: "Emergency flood restoration plumber in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 103,
    promptTemplate: "Emergency tree removal after storm damage in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  {
    rank: 104,
    promptTemplate: "24-hour emergency air conditioning repair in {location}?",
    category: "emergency",
    expectedMentionType: "recommended",
  },
  // --- pricing (10) ---
  {
    rank: 105,
    promptTemplate: "How much does emergency plumbing cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 106,
    promptTemplate: "What is a fair price for an electrician callout in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 107,
    promptTemplate: "How much does a bathroom renovation cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 108,
    promptTemplate: "Average cost of a granny flat build in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 109,
    promptTemplate: "How much does split system installation cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 110,
    promptTemplate: "Cost of solar panel installation in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 111,
    promptTemplate: "How much does roof replacement cost in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 112,
    promptTemplate: "What is the hourly rate for a plumber in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 113,
    promptTemplate: "How much does Colorbond fencing cost per metre in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  {
    rank: 114,
    promptTemplate: "Average cost of a kitchen renovation in {location}?",
    category: "pricing",
    expectedMentionType: "listed",
  },
  // --- reviews (6) ---
  {
    rank: 115,
    promptTemplate: "Which plumbing companies in {location} have the best reviews?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 116,
    promptTemplate: "Best-reviewed electricians in {location} on Google?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 117,
    promptTemplate: "What do customers say about {brand}?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  {
    rank: 118,
    promptTemplate: "Best-reviewed builders in {location} on hipages?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 119,
    promptTemplate: "Which HVAC companies in {location} have 5-star reviews?",
    category: "reviews",
    expectedMentionType: "listed",
  },
  {
    rank: 120,
    promptTemplate: "What are the reviews for {brand} on Google and Product Review?",
    category: "reviews",
    expectedMentionType: "recommended",
  },
  // --- compliance (4) ---
  {
    rank: 121,
    promptTemplate: "Licensed plumbers in {location} — how do I check their licence?",
    category: "compliance",
    expectedMentionType: "listed",
  },
  {
    rank: 122,
    promptTemplate: "Is {brand} properly licensed and insured for plumbing in Australia?",
    category: "compliance",
    expectedMentionType: "recommended",
  },
  {
    rank: 123,
    promptTemplate: "Who does compliance certificates for gas appliances in {location}?",
    category: "compliance",
    expectedMentionType: "listed",
  },
  {
    rank: 124,
    promptTemplate: "How do I verify a builder's licence in {location}?",
    category: "compliance",
    expectedMentionType: "listed",
  },
] as const;
