-- Generated by scripts/ops/generate-citability-methods-prod-sql.ts from
-- db/seed/citability-methods/seed.ts (CITABILITY_METHODS, 47 rows).
-- Every value below is read from that module, not hand-typed. Do NOT
-- hand-edit this file -- regenerate it instead if the seed changes.
--
-- Idempotent: ON CONFLICT (method_key) DO UPDATE -- safe to re-run, and
-- doubles as the refresh path if a method's provenance/tier is corrected
-- later (DO UPDATE, not DO NOTHING, so a fix actually reaches prod on a
-- second run). effect_size_pct is explicitly NULLed on every row (see
-- header comment in the generator) -- it is invented precision, replaced
-- by impact_tier.
--
-- SRI: take a Neon snapshot/branch before running. Then run this file with
-- `psql -f db/prod-fixes/seed-citability-methods-prod.sql "$PROD_DATABASE_URL"`
-- (or paste into the Neon SQL editor, Production/neondb branch). NOT run
-- from Claude Code. Requires migrations 0034 AND 0035 already applied
-- (citation_url / source_type / impact_tier columns must exist) -- see
-- db/prod-fixes/0034-apply-prod.sql and db/prod-fixes/0035-apply-prod.sql.

BEGIN;

INSERT INTO citability_methods
  (method_key, title, description, source, effect_size_pct, effect_size_notes, applies_to, citation_url, source_type, impact_tier)
VALUES
  ('add-statistics-with-sources', 'Add cited statistics with source links', 'Include verifiable statistics with attribution from authoritative sources.', 'Aggarwal et al., GEO (Princeton, KDD 2024)', NULL, 'One of three top-performing GEO methods in the Princeton study (+30–40% Position-Adjusted Word Count)', '["ChatGPT","Perplexity","Gemini"]'::jsonb, 'https://arxiv.org/abs/2311.09735', 'research', 'high'),
  ('add-expert-quotes', 'Add attributed expert quotes', 'Include direct quotes from named industry experts with credentials.', 'Aggarwal et al., GEO (Princeton, KDD 2024)', NULL, 'One of three top-performing GEO methods in the Princeton study (+30–40% Position-Adjusted Word Count)', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, 'https://arxiv.org/abs/2311.09735', 'research', 'high'),
  ('add-authoritative-references', 'Add authoritative source references', 'Link to government, academic, or industry body sources.', 'Aggarwal et al., GEO (Princeton, KDD 2024)', NULL, 'Citing authoritative sources is part of the Princeton GEO study''s citation-addition method (+30–40% Position-Adjusted Word Count)', '["ChatGPT","Perplexity"]'::jsonb, 'https://arxiv.org/abs/2311.09735', 'research', 'high'),
  ('wikipedia-presence', 'Establish Wikipedia presence', 'Create or improve a neutral, well-sourced Wikipedia article.', 'VisibleAU Original', NULL, 'Vunnara estimate — Wikipedia pages are frequently cited by ChatGPT for factual and informational queries', '["ChatGPT"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('faq-in-main-content', 'Add FAQ blocks in main page content', 'Place FAQ content in the main body, not just schema markup.', 'VisibleAU Original', NULL, 'Vunnara estimate — FAQ content in the main body is more quotable than schema-only', '["ChatGPT","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('content-freshness', 'Update content within last 2 months', 'Keep pages updated with current dates, pricing, and contact info.', 'VisibleAU Original', NULL, 'Vunnara estimate — fresh content signals currency to AI crawlers', '["ChatGPT","Gemini","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('reddit-presence', 'Genuine Reddit participation', 'Contribute helpful answers in relevant subreddits.', 'VisibleAU Original', NULL, 'Vunnara estimate — Perplexity frequently draws on Reddit discussions for real-world opinions and experiences', '["Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('medium-articles', 'Publish how-to articles on Medium', 'Write practical guides linking back to service pages.', 'VisibleAU Original', NULL, 'Vunnara estimate — Gemini appears to favour accessible, first-party publishing platforms like Medium', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('linkedin-presence', 'Maintain active LinkedIn company page', 'Complete all sections and post regularly.', 'VisibleAU Original', NULL, 'Vunnara estimate — active company pages support entity recognition and professional credibility signals', '["ChatGPT"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('press-mentions', 'Earn press mentions in trade media', 'Pitch newsworthy stories to industry publications.', 'VisibleAU Original', NULL, 'Vunnara estimate — earned media mentions create independent corroboration that can survive citation drift', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('comparison-content', 'Publish comparison and vs content', 'Create detailed comparison pages for high-intent queries.', 'VisibleAU Original', NULL, 'Vunnara estimate — comparison and "best for" queries are frequently answered by LLMs', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('schema-organization', 'Add Organization schema markup', 'Include complete Organization JSON-LD with all key attributes.', 'VisibleAU Original', NULL, 'Helps Google AI Overviews indirectly via snippets', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('schema-local-business', 'Add LocalBusiness schema markup', 'Include LocalBusiness JSON-LD with NAP, hours, and service area.', 'VisibleAU Original', NULL, 'Strengthens local entity recognition', '["Gemini","ChatGPT"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('schema-faq-page', 'Add FAQPage schema markup', 'Structure FAQ content with FAQPage JSON-LD markup.', 'VisibleAU Original', NULL, 'Vunnara estimate — schema alone has limited impact without real content', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('schema-article', 'Add Article schema markup', 'Mark up blog and article pages with Article JSON-LD.', 'VisibleAU Original', NULL, 'Improves article snippet selection', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('llms-txt-file', 'Create and serve llms.txt', 'Provide a structured llms.txt file for AI crawler consumption.', 'VisibleAU Original', NULL, 'Emerging standard; early adoption signal', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('robots-allow-ai', 'Allow AI crawlers in robots.txt', 'Explicitly allow GPTBot, ClaudeBot, PerplexityBot access.', 'VisibleAU Original', NULL, 'Blocked bots cannot cite you at all', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('server-side-rendering', 'Ensure server-side rendering', 'Render content server-side so AI crawlers can read it.', 'VisibleAU Original', NULL, 'CSR pages invisible to most AI crawlers', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('answer-capsule-pattern', 'Use the answer capsule pattern', 'Follow question headings with a 20-25 word direct answer.', 'VisibleAU Original', NULL, 'Vunnara estimate — direct, well-formed answers are more likely to be quoted verbatim by AI engines', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('nap-consistency', 'Ensure NAP consistency across directories', 'Name, Address, Phone must match exactly across all listings.', 'VisibleAU Original', NULL, 'Inconsistent NAP confuses entity resolution', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('au-directory-presence', 'List on AU-specific directories', 'Submit to hipages, Yellow Pages AU, ServiceSeeking, Word of Mouth.', 'VisibleAU Original', NULL, 'AU directories weight local AI responses', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('google-business-profile', 'Complete Google Business Profile', 'Fill all GBP sections including services, hours, photos.', 'VisibleAU Original', NULL, 'GBP feeds Google AI Overviews for local queries', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('content-depth-1500', 'Ensure content depth (1500+ words)', 'Key service pages should have substantial, detailed content.', 'VisibleAU Original', NULL, 'Vunnara estimate — more substantial content gives AI engines more to cite', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('title-tag-optimization', 'Optimize title tags for AI queries', 'Include the primary service and location in page titles.', 'VisibleAU Original', NULL, 'Title tags used in snippet selection', '["Gemini","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('meta-description-quality', 'Write compelling meta descriptions', '50-160 character descriptions summarizing the page value proposition.', 'VisibleAU Original', NULL, 'Meta descriptions feed search snippet selection', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('canonical-tags', 'Set canonical tags correctly', 'Prevent duplicate content confusion with proper canonicalization.', 'VisibleAU Original', NULL, 'Prevents entity dilution from duplicate pages', '["Gemini","ChatGPT"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('og-tags-complete', 'Complete Open Graph tags', 'Include og:title, og:description, og:image on all pages.', 'VisibleAU Original', NULL, 'Social signals feed AI entity graphs', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('internal-linking', 'Strengthen internal linking structure', 'Link between related service pages with descriptive anchor text.', 'VisibleAU Original', NULL, 'Vunnara estimate — internal links help AI engines understand site structure and topical relationships', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('outbound-authority-links', 'Link to authoritative external sources', 'Reference government, academic, and industry body websites.', 'Aggarwal et al., GEO (Princeton, KDD 2024)', NULL, 'Citing authoritative external sources is part of the Princeton GEO study''s citation-addition method (+30–40% Position-Adjusted Word Count)', '["ChatGPT","Perplexity"]'::jsonb, 'https://arxiv.org/abs/2311.09735', 'research', 'high'),
  ('author-attribution', 'Add author bylines to content', 'Include named authors with credentials on articles and guides.', 'VisibleAU Original', NULL, 'Vunnara estimate — named author attribution signals expertise and accountability', '["ChatGPT","Claude"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('date-stamps', 'Add last-updated dates to content', 'Show when content was last reviewed or updated.', 'VisibleAU Original', NULL, 'Vunnara estimate — visible freshness signals support content recency assessment', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('suburb-specific-pages', 'Create suburb-specific landing pages', 'Build dedicated pages for each service area suburb.', 'VisibleAU Original', NULL, 'Suburb pages match local AI query patterns', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('remove-cta-overload', 'Reduce excessive CTAs', 'Keep CTAs under 7 per page to avoid spam signals.', 'VisibleAU Original', NULL, 'CTA overload correlates with lower AI citation rates', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('reduce-popup-density', 'Minimize popups and overlays', 'Remove or reduce intrusive popups that block content.', 'VisibleAU Original', NULL, 'Popups degrade content accessibility for crawlers', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('fix-broken-links', 'Fix broken outbound links', 'Ensure all external links resolve correctly.', 'VisibleAU Original', NULL, 'Broken links signal neglected content', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('reduce-ad-density', 'Reduce ad density on key pages', 'Keep ad containers under 3 per page on service pages.', 'VisibleAU Original', NULL, 'High ad density reduces content quality signals', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('remove-hidden-text', 'Remove hidden text and invisible content', 'Eliminate CSS-hidden text that could be flagged as manipulation.', 'VisibleAU Original', NULL, 'Hidden text triggers prompt injection detection', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('remove-prompt-injections', 'Remove prompt injection attempts', 'Eliminate any LLM-instruction text, invisible Unicode, or data-attr injections.', 'VisibleAU Original', NULL, 'Prompt injections can cause delisting', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('ai-txt-endpoint', 'Create .well-known/ai.txt endpoint', 'Publish machine-readable AI metadata at the emerging standard endpoint.', 'VisibleAU Original', NULL, 'Emerging standard; early adoption advantage', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('ai-summary-json', 'Create /ai/summary.json endpoint', 'Publish structured brand summary for AI systems.', 'VisibleAU Original', NULL, 'Structured data for AI consumption', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('ai-faq-json', 'Create /ai/faq.json endpoint', 'Publish FAQ data in machine-readable format for AI Q&A.', 'VisibleAU Original', NULL, 'Structured FAQ for AI systems', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('ai-service-json', 'Create /ai/service.json endpoint', 'Publish service catalogue for local AI search.', 'VisibleAU Original', NULL, 'Service data for local AI queries', '["ChatGPT","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('cdn-allow-ai', 'Configure CDN to allow AI crawlers', 'Ensure Cloudflare/Akamai/Vercel does not block AI bot user-agents.', 'VisibleAU Original', NULL, 'CDN blocks prevent all AI crawling', '["ChatGPT","Claude","Perplexity","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'high'),
  ('sitemap-xml', 'Maintain accurate sitemap.xml', 'Include all indexable pages in an up-to-date sitemap.', 'VisibleAU Original', NULL, 'Sitemap helps AI crawlers discover content', '["Gemini","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('hreflang-tags', 'Add hreflang tags for AU content', 'Signal Australian-specific content to search systems.', 'VisibleAU Original', NULL, 'Localisation signal for regional queries', '["Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'low'),
  ('reduce-boilerplate', 'Reduce boilerplate content ratio', 'Ensure unique content exceeds 40% of total page text.', 'VisibleAU Original', NULL, 'High boilerplate reduces content quality signals', '["ChatGPT","Perplexity"]'::jsonb, NULL, 'vunnara_estimate', 'medium'),
  ('abn-registration', 'Verify ABN with Australian Business Register', 'Ensure business name matches ABR records for entity verification.', 'VisibleAU Original', NULL, 'ABN verification strengthens AU entity signals', '["ChatGPT","Gemini"]'::jsonb, NULL, 'vunnara_estimate', 'medium')
ON CONFLICT (method_key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  source = EXCLUDED.source,
  effect_size_pct = EXCLUDED.effect_size_pct,
  effect_size_notes = EXCLUDED.effect_size_notes,
  applies_to = EXCLUDED.applies_to,
  citation_url = EXCLUDED.citation_url,
  source_type = EXCLUDED.source_type,
  impact_tier = EXCLUDED.impact_tier;

COMMIT;

-- After this runs: 47 rows in citability_methods, 4 with source_type =
-- 'research' and a real citation_url (all arxiv.org/abs/2311.09735,
-- Aggarwal et al.), 43 with source_type = 'vunnara_estimate' and
-- citation_url = NULL. Every row has a valid impact_tier
-- ('high'/'medium'/'low') and effect_size_pct = NULL. See
-- db/prod-fixes/seed-citability-methods-verify.sql for the exact
-- verification queries.
